### ISSUE TITLE
Singer.get_logger issue

### ISSUE THREAD

**Issue by leohokhei** [singer-io/singer-python#31]
Hello,

I am trying to create a target using the "getting started" guide.
However, my program terminated during the import process of "singer" module.
Details are below:
Traceback (most recent call last):
  File "tap_ip.py", line 5, in <module>
    import singer
  File "/usr/local/lib/python3.6/site-packages/singer/__init__.py", line 8, in <module>
    from singer import transform
  File "/usr/local/lib/python3.6/site-packages/singer/transform.py", line 7, in <module>
    LOGGER = singer.get_logger()
AttributeError: module 'singer' has no attribute 'get_logger'

Any help is appreciated.

Thanks.

**Comment by iterati** [comment]
Please update to 2.0.0 or downgrade to 1.9.7. 1.9.8 was released by mistake and has been removed from pypi.
